services:
  gamesreviews.web:
    build:
      context: ./backend
      dockerfile: src/GamesReviews.Web/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://*:8080      # Явно указываем URL
      - DOTNET_USE_POLLING_FILE_WATCHER=1  # Для горячей перезагрузки файлов
    container_name: GamesReviews_web_api
    depends_on:
      - db
  frontend: # Фронтенд
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Фронт доступен на http://localhost:3000
    container_name: GamesReviews_frontend
    depends_on:
      - gamesreviews.web
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: artemlol228666
      POSTGRES_DB: GamesReviews
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: GamesReviews_db
volumes:
  db_data:
